ECHO OFF

SET Path_s=c:\CASA\CDM\LaQuercia\
@ECHO ESEMPIO FOR SU CARTELLE RICORSIVA
@ECHO	EVIDENZIA TUTTI I FILE XLS NELLA CARTELLA %Path_s%
@ECHO   	E NELLE SUE SOTTOCARTELLE con il ciclo FOR /R



For /R %Path_s% %%G IN (*.XLS) do Echo "%%G" 


PAUSE